const products = [
  {
    category: 'Sweets',
    items: [
      {
        _id: 1,
        name: 'Chocolate Cake',
        price: 15.99,
        description: 'Rich chocolate cake',
        imageUrl: '/images/products/chocolate_cake.jpg',
      },
      {
        _id: 2,
        name: 'Colorful Macarons',
        price: 10.99,
        description: 'Assorted macarons in various flavors',
        imageUrl: '/images/products/macarons.jpg',
      },
      {
        _id: 3,
        name: 'Caramel Pudding',
        price: 7.99,
        description: 'Creamy caramel pudding',
        imageUrl: '/images/products/caramel_pudding.jpg',
      },
      {
        _id: 4,
        name: 'Strawberry Shortcake',
        price: 12.99,
        description: 'Classic strawberry shortcake',
        imageUrl: '/images/products/strawberry_shortcake.jpg',
      },
      {
        _id: 5,
        name: 'Fudge Brownies',
        price: 8.99,
        description: 'Dense and chocolatey fudge brownies',
        imageUrl: '/images/products/fudge_brownies.jpg',
      },
      {
        _id: 6,
        name: 'Vanilla Cupcakes',
        price: 6.99,
        description: 'Vanilla cupcakes with buttercream frosting',
        imageUrl: '/images/products/vanilla_cupcakes.jpg',
      },
    ],
  },
  {
    category: 'Meals',
    items: [
      {
        _id: 101,
        name: 'Chicken Pasta',
        price: 12.99,
        description: 'Creamy chicken pasta',
        imageUrl: '/images/products/chicken_pasta.jpg',
      },
      {
        _id: 102,
        name: 'Grilled Steak',
        price: 18.99,
        description: 'Juicy grilled steak with vegetables',
        imageUrl: '/images/products/steak.jpg',
      },
      {
        _id: 103,
        name: 'Herb-Roasted Chicken',
        price: 15.99,
        description: 'Tender herb-roasted chicken',
        imageUrl: '/images/products/herb_chicken.jpg',
      },
      {
        _id: 104,
        name: 'Salmon with Lemon',
        price: 19.99,
        description: 'Pan-seared salmon with lemon garnish',
        imageUrl: '/images/products/salmon.jpg',
      },
      {
        _id: 105,
        name: 'Vegetarian Lasagna',
        price: 13.99,
        description: 'Vegetarian lasagna with layers of veggies',
        imageUrl: '/images/products/vegetarian_lasagna.jpg',
      },
      {
        _id: 106,
        name: 'Beef Stir Fry',
        price: 14.99,
        description: 'Savory beef stir fry',
        imageUrl: '/images/products/beef_stir_fry.jpg',
      },
    ],
  },
  {
    category: 'Breads',
    items: [
      {
        _id: 201,
        name: 'Crusty Baguette',
        price: 3.99,
        description: 'Freshly baked crusty baguette',
        imageUrl: '/images/products/baguette.jpg',
      },
      {
        _id: 202,
        name: 'Sourdough Loaf',
        price: 5.99,
        description: 'Tangy sourdough loaf',
        imageUrl: '/images/products/sourdough.jpg',
      },
      {
        _id: 203,
        name: 'Croissants',
        price: 4.99,
        description: 'Flaky and buttery croissants',
        imageUrl: '/images/products/croissants.webp',
      },
      {
        _id: 204,
        name: 'Whole Wheat Rolls',
        price: 4.49,
        description: 'Healthy whole wheat rolls',
        imageUrl: '/images/products/wheat_rolls.jpg',
      },
      {
        _id: 205,
        name: 'Focaccia with Herbs',
        price: 5.99,
        description: 'Focaccia topped with herbs',
        imageUrl: '/images/products/focaccia.jpg',
      },
      {
        _id: 206,
        name: 'Pretzels',
        price: 3.49,
        description: 'Soft and salty pretzels',
        imageUrl: '/images/products/pretzel.jpg',
      },
    ],
  },
  {
    category: 'Butters',
    items: [
      {
        _id: 301,
        name: 'Peanut Butter',
        price: 3.99,
        description: 'Smooth and creamy peanut butter',
        imageUrl: '/images/products/peanut_butter.webp',
      },
      {
        _id: 302,
        name: 'Whipped Honey Butter',
        price: 4.99,
        description: 'Honey butter whipped to perfection',
        imageUrl: '/images/products/honey_butter.jpg',
      },
      {
        _id: 303,
        name: 'Garlic Herb Butter',
        price: 5.49,
        description: 'Butter infused with garlic and herbs',
        imageUrl: '/images/products/garlic_butter.jpg',
      },
      {
        _id: 304,
        name: 'Almond Butter',
        price: 6.99,
        description: 'Nutty almond butter',
        imageUrl: '/images/products/almond_butter.webp',
      },
      {
        _id: 305,
        name: 'Chocolate Spread',
        price: 4.99,
        description: 'Rich chocolate spread',
        imageUrl: '/images/products/chocolate_spread.jpg',
      },
      {
        _id: 306,
        name: 'Cashew Butter',
        price: 7.49,
        description: 'Creamy cashew butter',
        imageUrl: '/images/products/cashew_butter.JPG',
      },
    ],
  },
  {
    category: 'Others',
    items: [
      {
        _id: 401,
        name: 'Mixed Fruit Salad',
        price: 8.99,
        description: 'Freshly made fruit salad',
        imageUrl: '/images/products/fruit_salad.jpg',
      },
      {
        _id: 402,
        name: 'Jar of Pickles',
        price: 4.99,
        description: 'Crunchy homemade pickles',
        imageUrl: '/images/products/pickles.jpg',
      },
      {
        _id: 403,
        name: 'Cheese Platter',
        price: 14.99,
        description: 'Assorted cheeses on a platter',
        imageUrl: '/images/products/cheese_platter.jpg',
      },
      {
        _id: 404,
        name: 'Sushi Rolls',
        price: 12.99,
        description: 'Freshly prepared sushi rolls',
        imageUrl: '/images/products/sushi.jpg',
      },
      {
        _id: 405,
        name: 'Boiled Peanuts',
        price: 5.99,
        description: 'Delicious boiled peanuts',
        imageUrl: '/images/products/boiled_peanuts.jpg',
      },
      {
        _id: 406,
        name: 'Bowl of Guacamole',
        price: 7.49,
        description: 'Creamy guacamole dip',
        imageUrl: '/images/products/guacamole.jpg',
      },
    ],
  },
];

export default products;
